export const newsItems = [
  {
    id: "1",
    type: "Awards & Recognition",
    date: "2025-01-18",
    title: "Yugasa Builders Wins 'Developer of the Year' at Mumbai Real Estate Excellence Awards 2025",
    category: "Awards & Recognition",
    excerpt: "Recognized for outstanding contribution to sustainable construction and innovative residential projects across Mumbai metropolitan region.",
    content: "Yugasa Builders has been honored with the prestigious 'Developer of the Year' award at the Mumbai Real Estate Excellence Awards 2025. This recognition highlights our commitment to sustainable construction practices and innovative residential projects that have transformed the Mumbai metropolitan landscape.",
    image: "/luxury-construction-interior-lobby-with-wood-panel.jpg",
    featured: true,
    author: "Yugasa Media Team",
    readTime: "3 min read",
    tags: ["Awards", "Recognition", "Excellence"]
  },
  {
    id: "2",
    type: "Innovation",
    date: "2025-01-15",
    title: "Revolutionary Green Building Technology Reduces Construction Carbon Footprint by 40%",
    category: "Innovation",
    excerpt: "Yugasa Builders pioneers eco-friendly construction methods using recycled materials and renewable energy systems in all new projects.",
    content: "Our latest innovation in green building technology has achieved a remarkable 40% reduction in construction carbon footprint. By integrating recycled materials, renewable energy systems, and advanced sustainable construction methods, we're setting new industry standards for environmental responsibility.",
    image: "/sustainable-materials.jpg",
    featured: false,
    author: "Dr. Priya Sharma",
    readTime: "6 min read",
    tags: ["Sustainability", "Green Tech", "Innovation"]
  },
  {
    id: "3",
    type: "Industry Insights",
    date: "2025-01-12",
    title: "Mumbai Real Estate Market Shows 25% Growth in Premium Residential Segment",
    category: "Industry Insights",
    excerpt: "Latest market analysis reveals strong demand for luxury residential properties, with Yugasa projects leading the premium segment growth.",
    content: "The Mumbai real estate market has demonstrated exceptional resilience and growth, particularly in the premium residential segment. Our comprehensive market analysis shows a 25% year-over-year growth, with Yugasa projects consistently outperforming market averages and setting new benchmarks for luxury living.",
    image: "/modern-luxury-residence-exterior.jpg",
    featured: false,
    author: "Rajesh Mehta",
    readTime: "5 min read",
    tags: ["Market Analysis", "Growth", "Premium"]
  },
  {
    id: "4",
    type: "Company News",
    date: "2025-01-10",
    title: "Serenity Heights Phase 2 Launch: 150 Premium Apartments with Smart Home Integration",
    category: "Company News",
    excerpt: "Following the success of Phase 1, we're launching 150 new premium apartments featuring AI-powered home automation and sustainable design.",
    content: "Building on the tremendous success of Serenity Heights Phase 1, we're excited to announce the launch of Phase 2, featuring 150 premium apartments with cutting-edge smart home integration. Each unit incorporates AI-powered home automation systems and sustainable design principles that represent the future of residential living.",
    image: "/commercial-building-glass.jpg",
    featured: false,
    author: "Yugasa Development Team",
    readTime: "4 min read",
    tags: ["New Launch", "Smart Homes", "Premium"]
  },
  {
    id: "5",
    type: "Innovation",
    date: "2025-01-08",
    title: "AI and IoT Transforming Construction Project Management: A Case Study",
    category: "Innovation",
    excerpt: "How artificial intelligence and Internet of Things are revolutionizing construction timelines, quality control, and cost management.",
    content: "Our comprehensive case study demonstrates how AI and IoT technologies are fundamentally transforming construction project management. From predictive analytics for timeline optimization to real-time quality control monitoring, these technologies are delivering unprecedented improvements in efficiency and cost management.",
    image: "/construction-site-cranes.png",
    featured: false,
    author: "Amit Kumar",
    readTime: "7 min read",
    tags: ["AI", "IoT", "Technology"]
  },
  {
    id: "6",
    type: "Company News",
    date: "2025-01-05",
    title: "Yugasa Builders Partners with Leading Architects for Iconic Mumbai Skyline Project",
    category: "Company News",
    excerpt: "Strategic collaboration with internationally acclaimed architects to design a landmark 50-story mixed-use development in Bandra-Kurla Complex.",
    content: "We're proud to announce our strategic partnership with internationally acclaimed architects for an iconic 50-story mixed-use development in Bandra-Kurla Complex. This landmark project will redefine Mumbai's skyline while incorporating sustainable design principles and cutting-edge architectural innovation.",
    image: "/urban-redevelopment-aerial-construction.jpg",
    featured: false,
    author: "Yugasa Media Team",
    readTime: "4 min read",
    tags: ["Partnership", "Architecture", "Landmark"]
  },
  {
    id: "7",
    type: "Industry Insights",
    date: "2025-01-02",
    title: "Construction Industry Adopts Modular Building Techniques for Faster Project Delivery",
    category: "Industry Insights",
    excerpt: "Industry-wide shift towards prefabricated and modular construction methods reduces project timelines by 30% while maintaining quality standards.",
    content: "The construction industry is experiencing a significant transformation with the widespread adoption of modular building techniques. Our analysis shows that prefabricated and modular construction methods can reduce project timelines by up to 30% while maintaining the highest quality standards and improving cost efficiency.",
    image: "/news/news-2.png",
    featured: false,
    author: "Meera Joshi",
    readTime: "5 min read",
    tags: ["Modular", "Efficiency", "Innovation"]
  },
  {
    id: "8",
    type: "Company News",
    date: "2024-12-28",
    title: "Yugasa Foundation Launches Skill Development Program for Construction Workers",
    category: "Company News",
    excerpt: "Comprehensive training initiative aims to upskill 1000+ construction workers in modern building techniques and safety protocols.",
    content: "The Yugasa Foundation has launched an ambitious skill development program designed to upskill over 1000 construction workers in modern building techniques and advanced safety protocols. This comprehensive training initiative reflects our commitment to workforce development and industry advancement.",
    image: "/luxury-construction-interior-lobby-with-wood-panel.jpg",
    featured: false,
    author: "Yugasa Foundation",
    readTime: "3 min read",
    tags: ["CSR", "Training", "Skills"]
  },
  {
    id: "9",
    type: "Innovation",
    date: "2024-12-25",
    title: "Smart Building Materials: The Future of Sustainable Construction",
    category: "Innovation",
    excerpt: "Exploring next-generation building materials that adapt to environmental conditions and reduce energy consumption.",
    content: "The future of construction lies in smart building materials that can adapt to environmental conditions and significantly reduce energy consumption. Our research and development team has been pioneering the use of these innovative materials in our latest projects, achieving remarkable results in sustainability and performance.",
    image: "/coastal-villa-architecture.jpg",
    featured: false,
    author: "Dr. Anita Patel",
    readTime: "6 min read",
    tags: ["Smart Materials", "Sustainability", "Future Tech"]
  },
  {
    id: "10",
    type: "Industry Insights",
    date: "2024-12-22",
    title: "Digital Transformation in Construction: Trends and Opportunities",
    category: "Industry Insights",
    excerpt: "How digital technologies are reshaping the construction industry and creating new opportunities for growth and efficiency.",
    content: "Digital transformation is revolutionizing the construction industry, creating unprecedented opportunities for growth, efficiency, and innovation. From Building Information Modeling (BIM) to drone surveys and virtual reality planning, digital technologies are fundamentally changing how we approach construction projects.",
    image: "/modern-residential-interior.jpg",
    featured: false,
    author: "Vikram Singh",
    readTime: "5 min read",
    tags: ["Digital", "Transformation", "Technology"]
  },
  {
    id: "11",
    type: "Awards & Recognition",
    date: "2024-12-20",
    title: "Yugasa Builders Receives Green Building Certification for Eco-Friendly Practices",
    category: "Awards & Recognition",
    excerpt: "Latest project achieves LEED Platinum certification, setting new standards for environmental sustainability in construction.",
    content: "We're proud to announce that our latest residential project has achieved LEED Platinum certification, the highest level of green building recognition. This achievement underscores our unwavering commitment to environmental sustainability and sets new industry standards for eco-friendly construction practices.",
    image: "/architectural-details-monochrome.jpg",
    featured: false,
    author: "Yugasa Sustainability Team",
    readTime: "4 min read",
    tags: ["LEED", "Certification", "Sustainability"]
  },
  {
    id: "12",
    type: "Company News",
    date: "2024-12-18",
    title: "Yugasa Builders Expands Operations to Pune and Bangalore Markets",
    category: "Company News",
    excerpt: "Strategic expansion into two major metropolitan markets marks significant milestone in company's growth trajectory.",
    content: "Yugasa Builders is excited to announce our strategic expansion into the Pune and Bangalore markets, marking a significant milestone in our growth trajectory. This expansion will bring our expertise in sustainable construction and innovative design to two of India's most dynamic metropolitan regions.",
    image: "/construction-site-luxury-lobby.jpg",
    featured: false,
    author: "Yugasa Expansion Team",
    readTime: "4 min read",
    tags: ["Expansion", "Growth", "New Markets"]
  }
]