export const portfolioProjects = [
  {
    id: "1",
    title: "Serenity Heights",
    category: "Residential",
    location: "Bandra West, Mumbai",
    year: "2023",
    status: "Completed",
    units: "120 Apartments",
    image: "/modern-luxury-residence-exterior.jpg",
    description: "Premium residential complex with modern amenities and sustainable design features.",
    featured: true,
    meta: "3BHK · 2200 sqft · South City"
  },
  {
    id: "2",
    title: "The Grove Villas",
    category: "Luxury Villas",
    location: "Juhu, Mumbai", 
    year: "2023",
    status: "Completed",
    units: "12 Villas",
    image: "/luxury-villa-pool.png",
    description: "Exclusive beachfront villas with panoramic ocean views and private pools.",
    featured: true,
    meta: "Premium Villas · 4500 sqft"
  },
  {
    id: "3",
    title: "Ocean View Villas",
    category: "Luxury Villas",
    location: "Juhu, Mumbai", 
    year: "2023",
    status: "Completed",
    units: "12 Villas",
    image: "/coastal-villa-architecture.jpg",
    description: "Exclusive beachfront villas with panoramic ocean views and private pools.",
    featured: false,
    meta: "Luxury Villas · Ocean View"
  },
  {
    id: "4",
    title: "Tech Park Plaza",
    category: "Commercial",
    location: "BKC, Mumbai",
    year: "2022", 
    status: "Completed",
    units: "50,000 sq ft",
    image: "/commercial-building-glass.jpg",
    description: "State-of-the-art commercial complex with modern office spaces and amenities.",
    featured: false,
    meta: "Commercial · 50,000 sq ft"
  },
  {
    id: "5",
    title: "Urban Vista Redevelopment",
    category: "Redevelopment",
    location: "Central Mumbai",
    year: "2024",
    status: "Ongoing",
    units: "200 Units",
    image: "/urban-redevelopment-aerial-construction.jpg",
    description: "Complete redevelopment of old residential society into modern mixed-use complex.",
    featured: false,
    meta: "Redevelopment · 200 Units"
  },
  {
    id: "6",
    title: "Green Meadows",
    category: "Residential",
    location: "Thane",
    year: "2024",
    status: "Ongoing", 
    units: "80 Apartments",
    image: "/modern-residential-interior.jpg",
    description: "Eco-friendly residential project with green building certification and sustainable features.",
    featured: false,
    meta: "Residential · 80 Apartments"
  },
  {
    id: "7",
    title: "Heritage Restoration",
    category: "Heritage",
    location: "Fort, Mumbai",
    year: "2024",
    status: "Ongoing",
    units: "Heritage Building",
    image: "/architectural-details-monochrome.jpg",
    description: "Careful restoration of heritage building maintaining original architecture with modern amenities.",
    featured: false,
    meta: "Heritage · Restoration"
  }
]